# permissions for end users to edit customrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: customr-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-crd
    app.kubernetes.io/part-of: kubebuilder-crd
    app.kubernetes.io/managed-by: kustomize
  name: customr-editor-role
rules:
- apiGroups:
  - sayedppqq.dev.sayedppqq.dev
  resources:
  - customrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sayedppqq.dev.sayedppqq.dev
  resources:
  - customrs/status
  verbs:
  - get
