---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - sayedppqq.dev.sayedppqq.dev
  resources:
  - customrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sayedppqq.dev.sayedppqq.dev
  resources:
  - customrs/finalizers
  verbs:
  - update
- apiGroups:
  - sayedppqq.dev.sayedppqq.dev
  resources:
  - customrs/status
  verbs:
  - get
  - patch
  - update
